export const surnomsHomme: string[] = [
  // Ambianceurs & Show
  "Ambianceur né",
  "Le Showman",
  "Roi du boucan",
  "Chef de la joie",
  "Maître du micro",
  "Le boute-en-train",
  "Chauffeur de bus",
  "L'ambianceur gbé",
  "Le roi des basses",
  "Chef du convoi",
  "Capitaine Fun",
  "Le gars des sons",
  "Bouclier du bus",
  "Le DJ du trajet",
  "Le dynamiseur",
  "Guide de la fête",
  "Pilote de l'ambiance",
  "Le moteur JEF",
  "Gars de la zone",
  "Le boute-feu",
  "Master Class",
  "Le showmaker",
  "Chef des slogans",
  "Le gars chaud",
  "Moteur du bus",
  "Propulseur de vibe",
  "Le leader fun",
  "Expert en ambiance",
  "Le gars de Popo",
  "Commandant Show",
  // Chill & Détente
  "Le Ministre du Chill",
  "Roi du repos",
  "Monsieur Relax",
  "Le gars au calme",
  "Maître de la plage",
  "Le chiller pro",
  "Poseur de valise",
  "Le gars tranquille",
  "Champion du repos",
  "Expert en détente",
  "Zen attitude",
  "Le gars de l'ombre",
  "Monsieur Oklm",
  "Le vacancier",
  "Chill man",
  "Le gars posé",
  "Prince du sable",
  "Le gars doux",
  "Maître du hamac",
  "Le gars posley",
  "Monsieur Fraîcheur",
  "Le gars de l'eau",
  "Chilleur de luxe",
  "Le gars discret",
  "Monsieur Serein",
  "Le gars apaisé",
  "Fan de la côte",
  "Le gars de l'air",
  "Monsieur Paisible",
  "Poseur certifié",
  // Gisement & Elite FLLAC
  "Le Gisement pur",
  "L'Elite FLLAC",
  "Le linguiste VIP",
  "Gars de la com'",
  "Maître des mots",
  "Le génie FLLAC",
  "Le cadre UAC",
  "L'espoir du Sud",
  "Le garant JEF",
  "Gars du campus",
  "Monsieur Savoir",
  "L'intellectuel fun",
  "Le gars brillant",
  "Fierté de l'UAC",
  "Le pilier FLLAC",
  "L'atout du bus",
  "Le pro du gisement",
  "L'ambassadeur",
  "Le gars de la fac",
  "Monsieur Culture",
  "Le guide FLLAC",
  "L'érudit du Sud",
  "Le cerveau JEF",
  "Le crack du bus",
  "Gars de la langue",
  "Le représentant",
  "Monsieur Diplôme",
  "Le gars de valeur",
  "L'élite du Sud",
  "Le sage du groupe",
  // Sud & Histoire
  "Enfant de Ouidah",
  "Prince de Popo",
  "Fils du Sud",
  "L'historien",
  "Le gardien du Sud",
  "L'explorateur",
  "Le pèlerin JEF",
  "Roi de la côte",
  "Le gars du Mono",
  "Gars de la mer",
  "Le marin JEF",
  "Voyageur du Sud",
  "Le gars des palmes",
  "Capitaine Popo",
  "Guide de Ouidah",
  "Le fils du pays",
  "L'aventurier",
  "Le gars du port",
  "Maître de l'océan",
  "Le gars du sable",
  "Passager de l'Est",
  "Le gars de la lagune",
  "Fils de la terre",
  "L'héritier JEF",
  "Le gars du soleil",
  "Visiteur VIP",
  "Le gars des ondes",
  "Monsieur Voyage",
  "Le passager fier",
  "Enfant du littoral",
  // Style & Gars Propre
  "Le gars propre",
  "Monsieur Stylé",
  "Le gars sapé",
  "Champion du look",
  "Le beau gosse",
  "Monsieur Charisme",
  "Le gars élégant",
  "Fraîcheur du Sud",
  "Le gars soigné",
  "Monsieur Chic",
  "Le gars en forme",
  "Beau gosse JEF",
  "Monsieur Propre",
  "Le gars frais",
  "Star de la JEF",
  "Le gars de classe",
  "Monsieur Charme",
  "Le gars rayonnant",
  "Champion du style",
  "Le gars influent",
  "Monsieur VIP",
  "Le gars modèle",
  "Leader du groupe",
  "Le gars en vue",
  "Star du campus",
  "Le gars mimi",
  "Monsieur Prestige",
  "Le gars galant",
  "Monsieur Tendance",
  "Le Gars des Gars",
]

export const surnomsFemme: string[] = [
  // Ambiance & Show
  "La Star JEF",
  "Reine du boucan",
  "La go de l'ambiance",
  "Chef de file",
  "La meneuse fun",
  "L'ambianceuse",
  "Reine du trajet",
  "La go qui chauffe",
  "Capitaine de bus",
  "La go des sons",
  "Showgirl FLLAC",
  "La go dynamique",
  "Propulseuse JEF",
  "La go de la joie",
  "Reine du micro",
  "La go pimentée",
  "Moteur de la fête",
  "La go éclatante",
  "Guide de l'ambiance",
  "Reine des slogans",
  "La go du show",
  "Madame Energie",
  "La go motivée",
  "Reine du gisement",
  "La go qui gère",
  "Madame Sourire",
  "La go du convoi",
  "Reine du Sud",
  "La go festive",
  "Star du bus",
  // Chill & Chic
  "La Reine du Chill",
  "Madame Relax",
  "La go posée",
  "Douceur du Sud",
  "La go tranquille",
  "Madame Oklm",
  "La go du sable",
  "Chilleuse de luxe",
  "La go discrète",
  "Madame Sereine",
  "La go au calme",
  "Petite perle",
  "La go paisible",
  "Madame Zen",
  "La go de l'air",
  "Douceur JEF",
  "La go du littoral",
  "Madame Fraîcheur",
  "La go soyeuse",
  "Reine du repos",
  "La go sereine",
  "Madame Vacance",
  "La go de luxe",
  "Reine de la plage",
  "La go chicsy",
  "Madame Détente",
  "La go lumineuse",
  "Reine du fleuve",
  "La go rayonnante",
  "Madame Sagesse",
  // Fierté FLLAC
  "Fierté FLLAC",
  "L'Elite JEF",
  "Madame Linguiste",
  "La go de la Com'",
  "L'intellectuelle",
  "La go brillante",
  "Reine du campus",
  "Fille de l'UAC",
  "L'ambassadrice",
  "La go diplômée",
  "Madame Savoir",
  "La crack JEF",
  "La go du gisement",
  "Fierté du Sud",
  "La go savante",
  "Madame Culture",
  "La go modèle",
  "L'atout du bus",
  "La go influente",
  "Madame Leader",
  "La go du futur",
  "Reine des mots",
  "La go appliquée",
  "Madame Référence",
  "La go exemplaire",
  "Pilier de la FLLAC",
  "La go de valeur",
  "Madame Talent",
  "La go porteuse",
  "L'espoir FLLAC",
  // Sud & Culture
  "Belle de Ouidah",
  "Star de Popo",
  "Fille du Sud",
  "La go du terroir",
  "Reine de l'histoire",
  "L'exploratrice",
  "La go voyageuse",
  "Nana du Sud",
  "La go du Mono",
  "Princesse du Sud",
  "La go des côtes",
  "Reine du soleil",
  "La go du pays",
  "Sirène de Popo",
  "Belle de la côte",
  "La go des ondes",
  "Madame Touriste",
  "La go du voyage",
  "Reine de l'évasion",
  "La go du chemin",
  "Madame Passage",
  "La go de l'eau",
  "Reine de la lagune",
  "La go dévouée",
  "Madame Découverte",
  "La go curieuse",
  "Reine du littoral",
  "La go radieuse",
  "Madame Aventure",
  "Perle de Ouidah",
  // Style & Beauté
  "La go propre",
  "Madame Stylée",
  "La go sapée",
  "Reine du look",
  "La belle mimi",
  "Madame Charisme",
  "La go élégante",
  "Fraîcheur JEF",
  "La go soignée",
  "Madame Chic",
  "La go divine",
  "Belle de la JEF",
  "Madame Classe",
  "La go fraîche",
  "Star de l'UAC",
  "La go sublime",
  "Madame Charme",
  "La go éclatante",
  "Reine du style",
  "La go de classe",
  "Madame Prestige",
  "La go tendance",
  "Reine du glamour",
  "La go en vue",
  "Madame Influence",
  "La go craquante",
  "Perle de la JEF",
  "La go coquette",
  "Madame Modèle",
  "La Go des Gos",
]

export function getSurnomAleatoire(genre: 'homme' | 'femme'): string {
  const liste = genre === 'homme' ? surnomsHomme : surnomsFemme
  return liste[Math.floor(Math.random() * liste.length)]
}